config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?
  post '/graphql', to: 'graphql#execute'
  root 'application#welcome'
  get 'about', to: 'application#about'

  resources :categories

  resources :styles do
    resources :likes
    collection do
      get :american
      get :german
      get :british
      get :belgian
      get :historical
      get :uncategorised
    end
  end

  resource :session, only: %i[new create destroy]

  get 'signup', to: 'users#new'

  resources :users do
    post 'generate_token'
  end
  post '/users/:id/create_api_key', to: 'users#create_api_key', as: 'create_user_api_key'
  delete '/users/:id/destroy_token/:token', to: 'users#destroy_api_token', as: 'destroy_user_token'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # relationships
  has_many :likes, dependent: :destroy
  has_many :liked_styles, through: :likes, source: :style
  has_many :api_client_sessions, dependent: :destroy

  has_secure_password

  before_save :sanitize_email
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }


  private

  def sanitize_email
    self.email = email.strip.downcase
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :require_signin, except: %i[new create]
  before_action :require_correct_user_or_admin, only: %i[edit update delete]
  before_action :require_admin, only: %i[index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @liked_styles = @user.liked_styles
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Thanks for signing up!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'Account saved!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create_api_key
    @user = User.find(params[:id])
    if current_user?(@user) || current_user.admin?
      @user.api_client_sessions.create.key
      redirect_to @user, notice: 'API client token generated successfully.'
    else
      redirect_to @user, alert: 'You are not authorized to perform this action.'
    end
  end

  def destroy_api_token
    @user = User.find(params[:id])
    @token_to_delete = ApiClientSession.find_by(user_id: params[:id], key: params[:token])
    if @token_to_delete.destroy
      redirect_to @user, status: :see_other, info: 'API Token successfully deleted'
    else
      redirect_to @user, status: :unprocessable_entity, alert: @user.errors.full_messages.join(', ')
    end
  end

  def destroy
    @user = User.find(params[:id])
    session[:user_id] = nil
    @user.destroy
    redirect_to root_url, status: :see_other, notice: 'Goodbye.'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end

  def require_correct_user_or_admin
    @user = User.find(params[:id])
    return if current_user?(@user) || current_user.admin?

    redirect_to root_url, alert: 'You do not have permission to edit or delete this user.'
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<section class="style-details pt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <%= form_with(model: user, local: true, class: "needs-validation", novalidate: "") do |f| %>
          <%= render "shared/errors", object: user %>

          <div class="card">
            <div class="card-header">
              <%= title.presence || "Account Form" %>
            </div>
              <div class="card-body">
                <div class="mb-3">
                  <%= f.label :name, class: 'form-label' %>
                  <%= f.text_field :name, class: 'form-control', autofocus: true %>
                </div>

                <div class="mb-3">
                  <%= f.label :email, class: 'form-label' %>
                  <%= f.email_field :email, class: 'form-control' %>
                </div>

                <div class="mb-3">
                  <%= f.label :password, class: 'form-label' %>
                  <%= f.password_field :password, class: 'form-control' %>
                </div>

                <div class="mb-3">
                  <%= f.label :password_confirmation, "Confirm Password", class: 'form-label' %>
                  <%= f.password_field :password_confirmation, class: 'form-control' %>
                </div>

                <div class="d-grid gap-2">
                  <%= f.submit user.new_record? ? "Create Account" : "Update Account", class: "btn btn-primary" %>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<%= render "form", user: @user, title: "Edit Account" %>

app/views/users/index.html.erb
<section class="style-details pt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h1><%= pluralize(@users.size, "User") %></h1>
        <ul class="users">
          <% @users.each do |user| %>
          <li>
            <%= link_to(user.name, user) %>
            created
            <%= time_ago_in_words(user.created_at) %> ago
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<%= render "form", user: @user, title: "Sign Up" %>

app/views/users/show.html.erb
<section class="style-details pt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h1><%= @user.name %></h1>
        <h2><%= mail_to(@user.email) %></h2>
        <br>

        <% if current_user?(@user) || current_user_admin? %>
          <% unless current_user?(@user) %>
            <div class="alert alert-warning" role="alert">
              You are viewing another user's account.
            </div>
          <% end %>
          <div class="action">
            <%= link_to "Edit account", edit_user_path(@user), class: "btn btn-primary" %>
            <%= link_to "Delete account", @user, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
          </div>
          <div class="mt-4">
          <h3>API Client Tokens</h3>
          <% @user.api_client_sessions.each_with_index do |acs, index| %>
            <div class="token-line mb-2" id="token-<%= index %>">
              <span class="badge bg-secondary">Token <%= index + 1 %>:</span>
              <span class="token-value d-none" id="token-value-<%= index %>"> <%= acs.key %> </span>
              <%= button_tag "Show", type: "button", class: "btn btn-info show-token-buttons", data: { index: index } %>
              <%= link_to "Delete", destroy_user_token_path(@user, acs.key), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
            </div>
          <% end %>
          <%= form_with url: create_user_api_key_path, method: :post, class: "d-inline" do |f| %>
            <%= f.submit "Generate New Token", class: "btn btn-secondary mt-2" %>
          <% end %>
        </div>
        <% end %>
        <br>

        <div class="api-usage-instructions">
          <h3>Using Your API Credentials</h3>
          <p>To authenticate with the API, include your API token in a `X-Beer-Authorization` request header.</p>
          <p>For example, to retreive a list of the first 3 categories: </p>
          <code>
            curl 'https://beers.fly.dev/graphql' \
            --header 'X-Beer-Authorization: <API_TOKEN>' \
            --header 'Content-Type: application/json' \
            --data '{"query":"query firstThree($num:Int!){\n  categories(first: $num){\n    nodes{\n      id\n      name\n    }\n    pageInfo{\n      hasNextPage\n      endCursor\n    }\n  }\n}","variables":{"num":3}}'
          </code>
        </div>
      </div>
      <% if current_user?(@user) || current_user_admin? %>
        <div class="col-md-4 sidebar-custom">
          <h3>Liked Styles</h3>
          <ul class="list-unstyled">
            <% @liked_styles.each do |style| %>
              <li><%= link_to style.name, style_path(style) %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</section>