config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?
  post '/graphql', to: 'graphql#execute'
  root 'application#welcome'
  get 'about', to: 'application#about'

  resources :categories

  resources :styles do
    resources :likes
    collection do
      get :american
      get :german
      get :british
      get :belgian
      get :historical
      get :uncategorised
    end
  end

  resource :session, only: %i[new create destroy]

  get 'signup', to: 'users#new'

  resources :users do
    post 'generate_token'
  end
  post '/users/:id/create_api_key', to: 'users#create_api_key', as: 'create_user_api_key'
  delete '/users/:id/destroy_token/:token', to: 'users#destroy_api_token', as: 'destroy_user_token'
end

app/views/layouts/_flash.html.erb
    <% flash.each do |type, msg| %>
      <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-auto bg-light py-3">
  <div class="container">
    <p class="text-center">
      Made with 🍺 by <a href="http://github.com/JimmyMcKegger">James</a>
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to "Home", root_path, class: "navbar-brand" %>
      <%= link_to "About", about_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <% if current_user %>
            <li class="nav-item">
              <%= link_to "All Styles", styles_path, class: "nav-link active" %>
            </li>
          <% end %>
          <% if current_user_admin? %>
            <li class="nav-item">
              <%= link_to "New Style", new_style_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "All Categories", categories_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "All Users", users_path, class: "nav-link active" %>
            </li>
          <% end %>
          <% if current_user %>
            <li>
              <%= link_to current_user.name, current_user, class: "nav-link active" %>
            </li>
            <li>
              <%= link_to "Sign Out", session_path, data: { turbo_method: :delete }, class: "nav-link active" %>
            </li>
          <% else %>
            <li>
              <%= link_to "Sign In", new_session_path, class: "nav-link active" %>
            </li>
            <li>
              <%= link_to "Sign Up", signup_path, class: "nav-link active" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Beer Styles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🍺</text></svg>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

 <body class="body d-flex flex-column min-vh-100" id="<%= 'landing-page' if controller_name == 'application' %>">
  <%= render "layouts/header" %>
  <%= render "layouts/flash" %>

  <% if controller_name == 'application' %>
    <%= yield %>
  <% else %>
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <%= yield %>
        </div>
        <div class="col-md-4">
        </div>
      </div>
    </div>
    <% end %>
    <%= render "layouts/footer" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>